### ISSUE TITLE
HaCTML Markdown support

### ISSUE THREAD

**Issue by jaredkhan** [hackersatcambridge/hac-website#110]
# If the issue is enhancement suggestion:

## What the enhancement is

HaCTML could use inbuilt markdown support for TextNode

## Why it could be helpful

This will make it much cleaner to use Markdown in HaCTML:

Currently:
`TextNode(Text(markdown: mdText).html, escapeLevel: .unsafeRaw)`

Proposal:
`TextNode(markdown: mdText)`

**Comment by Pinpickle** [comment]
I would propose that this should be in userland, not HaCTML core. I believe we should keep HaCTML as close to just rendering HTML as possible. If we say Markdown is useful enough to include in there, we'd have to let a whole bunch of other things in there that we're implementing at the moment in userland.

e.g. we could make our `Text` struct `Nodeable`

**Comment by jaredkhan** [comment]
Okay that's fair. Perhaps some more of what we've built out in user land should be formalised and moved into their own libraries though. e.g. the MVVM stuff that's currently very loosely defined. Anyway that's a separate conversation, closing this
