### ISSUE TITLE
Explore Codable for Event structs

### ISSUE THREAD

**Issue by CharlieCrisp** [hackersatcambridge/hac-website#138]
Swift provides an interface, [Codable](https://developer.apple.com/documentation/swift/codable), which provides functionality to serialize (and deserialize structs) to JSON.

Currently, when we upload an `Event` via our API, we attempt to deserialize the JSON by attempting a lot of casts in `EventApiController.swift` but we could potentially do this with a lot less code using the `RouterRequest.read(as:)` which [Kitura provides](https://ibm-swift.github.io/Kitura/Classes/RouterRequest.html#/s:6Kitura13RouterRequestC4readxxm2as_tKs9DecodableRzlF).

**Comment by jaredkhan** [comment]
@CharlieCrisp could you add some detail of what specific problems you ran into here?

**Comment by CharlieCrisp** [comment]
So when I gave this a go, the `read(as:)` function was just returning `nil` every time (I think). However, if I hardcoded the same JSON as a string and used `JSONDecoder` directly then it would work fine. I never managed to work out whether the error was on my end or Kitura's.

**Comment by moosichu** [comment]
Also related to issue #117
