### ISSUE TITLE
Define a better notion of Color

### ISSUE THREAD

**Issue by CharlieCrisp** [hackersatcambridge/hac-website#139]
Currently, we use strings to encode colors for anything UI-Related. Swift has a `UIColor` [object](https://developer.apple.com/documentation/uikit/uicolor) but this cannot be used outside the scope of iOS development (I believe).
It would be great to have a better notion of color that would provide us with more compile-time safety!

**Comment by moosichu** [comment]
@CharlieCrisp please put a priority here!
