### ISSUE TITLE
Show the time of Workshop when displaying `Today` label

### ISSUE THREAD

**Issue by moosichu** [hackersatcambridge/hac-website#162]
It would be really nice when showing something like this:
![image](https://user-images.githubusercontent.com/10348641/33173901-c31a929c-d04d-11e7-994e-1c82d0f7303a.png)

If we could have the time of a workshop displayed. 
So instead of `Today` it showed `Today at 1:30pm`.

**Comment by moosichu** [comment]
I good place to start would be to look at `Sources/HaCWebsiteLib/ViewModels/LandingPage/EventFeature.swift`

**Comment by moosichu** [comment]
![image](https://user-images.githubusercontent.com/10348641/33174082-6d087896-d04e-11e7-8acb-58486e459e22.png)

**Comment by jaredkhan** [comment]
Closed in #246
