### ISSUE TITLE
Served content should be gzipped

### ISSUE THREAD

**Issue by jaredkhan** [hackersatcambridge/hac-website#18]
https://github.com/IBM-Swift/Kitura-Compression

**Comment by moosichu** [comment]
Is this related to issue #51 ?

**Comment by jaredkhan** [comment]
@moosichu Related but they do not depend on each other. 'Minification' ( as mentioned in #51 ) is referring to killing the unnecessary whitespace, name mangling CSS, etc in static resources. GZIP is over the wire compression.

**Comment by moosichu** [comment]
@jaredkhan Issue #51 is simply "Optimise production build with LIST OF STUFF etc.", I think this falls under it. ;)
