### ISSUE TITLE
Markdown transformations for workshop notes

### ISSUE THREAD

**Issue by jaredkhan** [hackersatcambridge/hac-website#192]
Related to issue #157 
## What the enhancement is
Workshop content now live in standalone repositories, e.g. https://github.com/hackersatcambridge/workshop-example

A principal piece of this content is the notes which accompany the workshop. One can embed images in these notes using relative URLs and storing the images in the images directory. See [the example notes](https://github.com/hackersatcambridge/workshop-example/tree/master/content/notes).

Currently, images embedded in workshop [notes] can't be displayed on the website. To make this possible we will want to copy images from the images directory to some place they can be served to the public (it's probably bad luck to serve them directly from GitHub) and then rewrite the markdown to point to the public copies of the images instead of using the relative URLs.

Roughly what this involves:

      // get all image URLs in notes.md
        // If relative URL
          // check that image exists
          // copy image over
          // rewrite the markdown
        // If absolute
          // Check that the URL is reachable, throw error if not
      // get all hyperlink URLs in notes.md
        // If relative
          // Throw an error, Notes need to be a single Markdown file
        // If absolute
          // Check that the URL is reachable, throw error if not

**Comment by moosichu** [comment]
Why do you think it's bad luck to serve images directly from GitHub? (out of interest)

Something of interest: https://rawgit.com/

**Comment by jaredkhan** [comment]
Just because it’s not designed for image hosting. We can use rawgit but that will mean having to keep track of the latest commit for each workshop repo and using that in the rawgit url (because rawgit caches permanently based on url) 
This is definitely possible it just seems like a pain

**Comment by moosichu** [comment]
TBH I agree! I just wanted a written record of the reasons. ;)

**Comment by jaredkhan** [comment]
https://github.com/loiclec/Apodimark
Looks promising for finding the URLs in the markdown so that we can transform them
