### ISSUE TITLE
Use Yarn instead of NPM

### ISSUE THREAD

**Issue by moosichu** [hackersatcambridge/hac-website#2]
https://yarnpkg.com/lang/en/

**Comment by moosichu** [comment]
For some reason gulp-cli won't work on my Linux machine if installed using Yarn, needs investigating... :(

**Comment by moosichu** [comment]
Haven't left the grasp of npm completely yet.

**Comment by Pinpickle** [comment]
@moosichu where are we still under its clutches?

**Comment by moosichu** [comment]
@Pinpickle In installing yarn itself, the reason you gave for that is reasonable. But I still think it is work keeping this issue open. Especially as it's a non-ideal situation.

**Comment by Pinpickle** [comment]
@moosichu can we open a new issue for that? Seems like we're combining some unrelated things to me

**Comment by moosichu** [comment]
@Pinpickle good point.
