### ISSUE TITLE
Add syntax highlighting for code in workshop notes

### ISSUE THREAD

**Issue by moosichu** [hackersatcambridge/hac-website#221]
Essentially, source markdown like this:
```markdown

```java
public int fib(int n) {
  if(n <= 1) {
    return n;
  }
  int fib = 1;
  int prevFib = 1;
  for(int i=2; i<n; i++) {
    int temp = fib;
    fib+= prevFib;
    prevFib = temp;
  }
  return fib;
}
\```

```

Should have syntax highlighting appropriate to the language used. Currently, the result looks like this:

![image](https://user-images.githubusercontent.com/10348641/35807935-297cf8d2-0a7c-11e8-95fe-64cddea8cfa8.png)

**Comment by Pinpickle** [comment]
This can either be done server-side (there isn't much available in the way of Swift) or client side with some popular highlighting libraries:

- https://highlightjs.org/
- http://prismjs.com/
