### ISSUE TITLE
Need a database representation of 'Events'

### ISSUE THREAD

**Issue by jaredkhan** [hackersatcambridge/hac-website#23]
'Events' are things that are advertised with a time and date and any other additional information necessary. We need a representation of events for the website that allows for referencing of `Workshop`s and Facebook events.

**Comment by Pinpickle** [comment]
Ideas for things that should be in events:

- Cover image
- Link to FB event
- Link to workshop page (or with contents embedded)
- Location
  - As "Google Maps aware" with address and location
  - As "building aware" with room number etc
- Time
- Description that is bound to the event and not the workshop (e.g. "there will be pizza", "happy halloween", etc...)

**Comment by CharlieCrisp** [comment]
@Pinpickle currently we've also got a `category` section for our events' `Postcard`s. I think this is probably also a good idea for `Event`s to have. 

Also, why the distinction between general event description and technical description? Is there a benefit of keeping these separate?

**Comment by Pinpickle** [comment]
@CharlieCrisp maybe the `category` for events needs to be a subset of those available for `PostCard`? While `hackathon` and `workshop` are useful for events, I can't think of a case for `hackathon` (and thinking ahead, `blog-post`)

Are you asking for why we're separating workshops from events? The goal is to make workshops completely self-standing as it is possible for us to run the same workshop more than once. This will allow us to reuse that content, and also make the workshop pages useful in their own right all year round.

Another way of putting it:

- The audience for our event pages is people in Cambridge
- The audience for our workshop pages is anyone in the world interested in CS

**Comment by CharlieCrisp** [comment]
One thing we haven't considered here is the database representation of past projects e.g. videos, workshop videos, blogs etc. 

For these things, we would not need `TTL`s etc. but we may need other information?

**Comment by jaredkhan** [comment]
Videos and blogs should probably be independent of this, since they aren't events. Perhaps they can have publication dates tied to them and they become 'updates' and can be added to an update stream.
