### ISSUE TITLE
Replace "light" and "dark" text over features with a dark box with light text

### ISSUE THREAD

**Issue by Pinpickle** [hackersatcambridge/hac-website#239]
Currently, we have text on top of our feature on the home page to display the date. To accommodate for different coloured images, that text can be either "dark" or "light". While a nice design feature, this is a pain to work with. The text should be background-agnostic, eg a dark box and light text.

Here is the code where we create the text on top:

https://github.com/hackersatcambridge/hac-website/blob/master/Sources/HaCWebsiteLib/Views/LandingPage/EventFeature.swift#L29-L44

**Comment by jaredkhan** [comment]
Note this is priority high because it blocks having automatically generated feature images
