### ISSUE TITLE
Home page about copy

### ISSUE THREAD

**Issue by Pinpickle** [hackersatcambridge/hac-website#36]
We have some simple home page about copy in the works but our home page needs to describe who we are and what we do in an obvious way to newcomers:

- A brief statement of our mission
- An explanation of the kinds of events we run
- An explanation of the kinds of projects we create

**Comment by moosichu** [comment]
On it :)

**Comment by moosichu** [comment]
Closed by PR #67 - will create a new issue for a Non-MVP version with more info.
