### ISSUE TITLE
Workshop launch tracker

### ISSUE THREAD

**Issue by Pinpickle** [hackersatcambridge/hac-website#40]
This is tracking all of the issues we need to solve for us to get workshops into a useable state on the website.

- [x] #156 
- [x] #157 
- [x] #158 
- [x] #159 
- [x] #197 
- [x] #198
- [x] #199
- [x] #211

**Comment by jaredkhan** [comment]
Broken down into:
#156 #157 #158 #159 #160 #161

**Comment by Pinpickle** [comment]
@jaredkhan I edited this issue to make it a tracker for those ones

**Comment by Pinpickle** [comment]
I'm moving #160 and #161 out of this as they are not blocking a launch of workshops

**Comment by jaredkhan** [comment]
Workshops are launched! 🚀
