### ISSUE TITLE
Pages hang on reloading after Swift changes

### ISSUE THREAD

**Issue by jaredkhan** [hackersatcambridge/hac-website#43]
Looks like this might be caused by Livereload running too soon

**Comment by Pinpickle** [comment]
Do you think we could listen for "server is listening on port xxxx" in stdout?

**Comment by jaredkhan** [comment]
We could do that. There's milliseconds in it though, I think a short delay is a decent option

**Comment by jaredkhan** [comment]
Actually @Pinpickle, your idea was neater to implement than I thought (and far more appealing than my idea) so I ran with it in #44

**Comment by Pinpickle** [comment]
Fixed by #44
