### ISSUE TITLE
Optimise production build with cache-busting

### ISSUE THREAD

**Issue by Pinpickle** [hackersatcambridge/hac-website#51]

**Comment by moosichu** [comment]
This issue could probably be broken down

**Comment by moosichu** [comment]
@Pinpickle What is the list of stuff this can be broken down into?

**Comment by Pinpickle** [comment]
I would say just CSS minification and cace-busting in this case.

We'd get both of those if we added [Webpack](https://webpack.js.org/) to our build.

**Comment by Pinpickle** [comment]
Split up minification into #141 so we can just tackle cache-busting for now
