### ISSUE TITLE
Add error handling for routes (with error pages)

### ISSUE THREAD

**Issue by Pinpickle** [hackersatcambridge/hac-website#58]
Should handle not found pages and errors thrown in routes.

Need a pretty page to tell our lovely users when something has gone wrong.

This issue is about the backend part of this, see issue #78 for the frontend.

**Comment by jaredkhan** [comment]
Alright have spent too much time and am none-the-wiser on how to implement a simple 404 catcher 🙄
Unassigning myself for now and recommending we don't attempt to do this in time for the fair
